Repository sepandhaghighi/pyrgg, pull requests merged in 2024-04, with the labels that each got.

#160 Engines Modularized
  .github/workflows/test.yml
  CHANGELOG.md
  otherfile/profiles/erg_profile.py
  otherfile/profiles/pyrgg_profile.py
  otherfile/pyrgg_profile.py
  pyrgg/__init__.py
  pyrgg/__main__.py
  pyrgg/engines/__init__.py
  pyrgg/engines/erdos_reyni_gilbert.py
  pyrgg/engines/pyrgg.py
  pyrgg/functions.py
  pyrgg/params.py
  pyrgg/test.py
  setup.py
  test/engines/erdos_reyni_gilbert_test.py
  test/engines/pyrgg_test.py
  test/functions_test.py
  test/graph_gen_test.py
Labels: enhancement

#161 Modern templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CHANGELOG.md
  otherfile/RELEASE.md
  otherfile/version_check.py
Labels: enhancement, document

#162 Minor edits
  .github/CODE_OF_CONDUCT.md
  .github/FUNDING.yml
  .github/workflows/test.yml
  AUTHORS.md
  CHANGELOG.md
  README.md
  TODO.md
  otherfile/donate-button.png
  otherfile/meta.yaml
  pyrgg/params.py
  setup.py
  test/functions_test.py
Labels: document
