Repository sepandhaghighi/pyrgg, pull requests merged in 2024-11, with the labels that each got.

#182 Logger Updated
  CHANGELOG.md
  pyrgg/engines/erdos_reyni.py
  pyrgg/engines/erdos_reyni_gilbert.py
  pyrgg/engines/pyrgg.py
  pyrgg/functions.py
  test/engines/erdos_reyni_gilbert_test.py
Labels: enhancement

#184 Fix/pypi badge
  CHANGELOG.md
  README.md
Labels: document, minor

#185 Minor edits
  CHANGELOG.md
  README.md
Labels: document, minor

#186 Version 1.6
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  PYRGG.spec
  README.md
  SECURITY.md
  otherfile/Version.rc
  otherfile/meta.yaml
  otherfile/version_check.py
  pyrgg/params.py
  setup.py
Labels: release

#187 Website v1.6
  index.html
Labels: website
