Repository sepandhaghighi/pyrgg, pull requests merged in 2024-10, with the labels that each got.

#178 README updated with Erdos Reyni engine description
  README.md
Labels: document

#179 Minor edits
  AUTHORS.md
  CHANGELOG.md
  README.md
  otherfile/Version.rc
  pyrgg/__init__.py
  pyrgg/__main__.py
  pyrgg/graph_gen.py
  pyrgg/params.py
  test/functions_test.py
Labels: document, minor

#180 Build system
  CHANGELOG.md
  README.md
  build_exe.bat
  otherfile/RELEASE.md
Labels: document, minor

#181 Python 3.13
  .github/workflows/test.yml
  CHANGELOG.md
  setup.py
Labels: test

#183 Add/limit gh action run
  .github/workflows/test.yml
  CHANGELOG.md
Labels: test
