Repository sepandhaghighi/pyrgg, pull requests merged in 2025-05, with the labels that each got.

#189 New Engine: Stochastic Block Model (`sbm`)
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  otherfile/profiles/sbm_profile.py
  pyrgg/__main__.py
  pyrgg/engines/stochastic_block_model.py
  pyrgg/functions.py
  pyrgg/params.py
  test/engines/stochastic_block_model_test.py
  test/functions_test.py
Labels: enhancement, new feature

#191 `Ubuntu-20.04` --> `Ubuntu-22.04`
  .github/workflows/publish_conda.yaml
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  CHANGELOG.md
  build_exe.bat
  otherfile/RELEASE.md
  otherfile/meta.yaml
  setup.py
Labels: test

#192 Version 1.7
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  PYRGG.spec
  README.md
  SECURITY.md
  otherfile/Version.rc
  otherfile/meta.yaml
  otherfile/version_check.py
  pyrgg/params.py
  setup.py
Labels: release

#193 Website v1.7
  donate.html
  index.html
Labels: website

#194 Cite
  CHANGELOG.md
  README.md
Labels: document

#195 SBM Engine Enhancement
  CHANGELOG.md
  pyrgg/functions.py
  pyrgg/params.py
Labels: enhancement, document
